version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "malek-week5-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fh54iz3nan0g"
s3_prefix = "malek-week5-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProductsTableName=\"products-malek-table\" SubscriptionsTableName=\"subscriptions-malek-table\""
image_repositories = []
